(function(){
  'use strict';
  const ADMIN_EMAILS=new Set(['ezemariaezemaria77@gmail.com','xeranraptor@gmail.com']);
  const auth=window.xeroaiAuth, db=window.xeroaiDb, $=id=>document.getElementById(id);
  let users=[], payments=[], currentUser=null, adminEmail='';
  const esc=v=>String(v==null?'':v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const dateValue=v=>v&&typeof v.toDate==='function'?v.toDate():(v?new Date(v):null);
  const formatDate=v=>{const d=dateValue(v);return d&&!isNaN(d)?d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'—'};
  const formatDateTime=v=>{const d=dateValue(v);return d&&!isNaN(d)?d.toLocaleString(undefined,{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—'};
  const statusOf=u=>String(u.subscriptionStatus||'').toLowerCase();
  const active=u=>statusOf(u)==='active'&&(!u.subscriptionExpiresAt||(dateValue(u.subscriptionExpiresAt)||new Date(0))>new Date());
  const trial=u=>{const d=dateValue(u.trialEndDate);return !active(u)&&!!d&&d>new Date()};
  const status=u=>active(u)?['active','Active']:trial(u)?['trial','Trial']:['inactive',u.subscriptionStatus||'Inactive'];
  const sortNewest=(a,b)=>(dateValue(b.createdAt)?.getTime()||0)-(dateValue(a.createdAt)?.getTime()||0);
  const setText=(id,v)=>{if($(id))$(id).textContent=String(v??'—')};
  function notice(msg,kind=''){const n=$('notice');n.textContent=msg;n.className='notice'+(kind?' '+kind:'');n.hidden=false;setTimeout(()=>{if(n.textContent===msg)n.hidden=true},6000)}
  function userNotice(msg,kind=''){const n=$('userNotice');n.textContent=msg;n.className='notice'+(kind?' '+kind:'');n.hidden=false;setTimeout(()=>{if(n.textContent===msg)n.hidden=true},6000)}
  function render(){
    const q=$('userSearch').value.trim().toLowerCase(), f=$('statusFilter').value;
    let list=users.filter(u=>{const [s]=status(u);const matchesStatus=f==='all'||s===f;const hay=[u.fullName,u.email,u.accountId,u.country,u.phone,u.defaultMarket].map(v=>String(v||'').toLowerCase()).join(' ');return matchesStatus&&(!q||hay.includes(q))});
    setText('userSummary',`${list.length} shown · ${users.length} total`);
    const body=$('usersTable');
    if(!list.length){body.innerHTML='<tr><td colspan="7" class="empty">No users match your search.</td></tr>';return}
    body.innerHTML=list.slice(0,300).map(u=>{const [cls,label]=status(u);const date=trial(u)?formatDate(u.trialEndDate):(u.subscriptionExpiresAt?formatDate(u.subscriptionExpiresAt):'—');return `<tr class="clickable-row" data-id="${esc(u.id)}"><td><div class="user-name">${esc(u.fullName||'Unnamed user')}</div><div class="user-email">${esc(u.email||'No email stored')}</div></td><td class="mono">${esc(u.accountId||'—')}</td><td>${esc(u.country||'—')}</td><td><span class="status ${cls}">${esc(label)}</span></td><td>${date}</td><td>${formatDate(u.createdAt)}</td><td><button class="row-action" data-open="${esc(u.id)}">View</button></td></tr>`}).join('');
    body.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openUser(e.currentTarget.dataset.open)}));
    body.querySelectorAll('tr[data-id]').forEach(r=>r.addEventListener('click',()=>openUser(r.dataset.id)));
  }
  async function load(){
    $('refreshBtn').disabled=true;
    try{const snap=await db.collection('users').get();users=snap.docs.map(d=>({id:d.id,...d.data()})).sort(sortNewest);await loadPayments();render()}
    catch(e){console.error(e);notice('Could not load users. Confirm the admin Firestore rules are deployed.');$('usersTable').innerHTML='<tr><td colspan="7" class="empty">Unable to load users.</td></tr>'}
    finally{$('refreshBtn').disabled=false}
  }
  async function loadPayments(){try{const snap=await db.collectionGroup('receipts').get();payments=snap.docs.map(d=>({id:d.id,userId:d.ref.parent.parent.id,...d.data()}));}catch(e){payments=[];console.warn(e)}}
  async function audit(action){try{await db.collection('admin_audit').add({action,targetUserId:currentUser?.id||'',targetEmail:currentUser?.email||'',adminEmail,createdAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(e){console.warn(e)}}
  async function openUser(id){
    const u=users.find(x=>x.id===id);if(!u)return;currentUser=u;
    setText('modalTitle',u.fullName||'Unnamed user');setText('modalSubtitle',u.email||'No email stored');setText('detailAccountId',u.accountId);setText('detailStatus',status(u)[1]);setText('detailExpiry',formatDate(u.subscriptionExpiresAt));setText('detailTrialEnd',formatDate(u.trialEndDate));setText('detailCountry',u.country);setText('detailTimezone',u.timezone);setText('detailMarket',u.defaultMarket);setText('detailPhone',u.phone);setText('detailJoined',formatDate(u.createdAt));
    $('detailPayments').innerHTML='<div class="empty">Loading…</div>';$('detailActivity').innerHTML='<div class="empty">Loading…</div>';$('userModal').hidden=false;document.body.classList.add('modal-open');
    const ps=payments.filter(p=>p.userId===u.id).sort((a,b)=>(dateValue(b.createdAt)?.getTime()||0)-(dateValue(a.createdAt)?.getTime()||0));
    setText('detailPaymentState',ps.some(p=>!p.status)?'Payment pending review':ps.length?'Submission history':'No submissions');
    $('detailPayments').innerHTML=ps.length?ps.map(p=>{const st=p.status==='approved'?'approved':p.status==='rejected'?'rejected':'pending';const label=st==='approved'?'Approved':st==='rejected'?'Rejected':'Pending review';return `<div class="detail-item"><div><strong>${label}</strong><small>${esc(formatDateTime(p.createdAt))}</small></div><div class="payment-actions">${!p.status?`<button class="primary-btn small" data-approve="${esc(p.id)}">Approve</button><button class="danger-btn small" data-reject="${esc(p.id)}">Reject</button>`:`<span class="status ${st}">${label}</span>`}</div></div>`}).join(''):'<div class="empty">No payment submissions.</div>';
    $('detailPayments').querySelectorAll('[data-approve]').forEach(b=>b.addEventListener('click',()=>approve(b.dataset.approve)));
    $('detailPayments').querySelectorAll('[data-reject]').forEach(b=>b.addEventListener('click',()=>reject(b.dataset.reject)));
    try{const snap=await db.collection('users').doc(u.id).collection('activity').orderBy('createdAt','desc').limit(15).get();$('detailActivity').innerHTML=snap.empty?'<div class="empty">No activity recorded.</div>':snap.docs.map(d=>{const x=d.data();return `<div class="detail-item"><div>${esc(x.message||'Activity')}</div><small>${esc(formatDateTime(x.createdAt))}</small></div>`}).join('')}catch(e){$('detailActivity').innerHTML='<div class="empty">Activity could not be loaded.</div>'}
  }
  async function approve(receiptId){if(!currentUser)return;const days=Number($('subscriptionDuration').value)||30;const base=active(currentUser)&&dateValue(currentUser.subscriptionExpiresAt)>new Date()?dateValue(currentUser.subscriptionExpiresAt):new Date();const expiry=new Date(base.getTime()+days*86400000);if(!confirm(`Approve this payment and activate the subscription for ${days} days?`))return;try{const batch=db.batch();batch.update(db.collection('users').doc(currentUser.id),{subscriptionStatus:'active',subscriptionExpiresAt:firebase.firestore.Timestamp.fromDate(expiry)});batch.update(db.collection('users').doc(currentUser.id).collection('receipts').doc(receiptId),{status:'approved',reviewedAt:firebase.firestore.FieldValue.serverTimestamp(),reviewedBy:adminEmail});await batch.commit();await audit('Payment approved');userNotice('Payment approved and subscription activated.','success');await load();await openUser(currentUser.id)}catch(e){console.error(e);userNotice('Approval failed. Check Firestore rules.')}}
  async function reject(receiptId){if(!currentUser||!confirm('Reject this payment submission?'))return;try{await db.collection('users').doc(currentUser.id).collection('receipts').doc(receiptId).update({status:'rejected',reviewedAt:firebase.firestore.FieldValue.serverTimestamp(),reviewedBy:adminEmail});await audit('Payment rejected');userNotice('Payment marked as rejected.','success');await load();await openUser(currentUser.id)}catch(e){console.error(e);userNotice('Could not reject the payment. Check Firestore rules.')}}
  async function activate(){if(!currentUser)return;const days=Number($('subscriptionDuration').value)||30;const base=active(currentUser)&&dateValue(currentUser.subscriptionExpiresAt)>new Date()?dateValue(currentUser.subscriptionExpiresAt):new Date();const expiry=new Date(base.getTime()+days*86400000);if(!confirm(`Activate or extend this subscription by ${days} days?`))return;try{await db.collection('users').doc(currentUser.id).update({subscriptionStatus:'active',subscriptionExpiresAt:firebase.firestore.Timestamp.fromDate(expiry)});await audit(`Subscription activated / extended for ${days} days`);userNotice('Subscription updated.','success');await load();await openUser(currentUser.id)}catch(e){console.error(e);userNotice('Could not update the subscription.')}}
  async function deactivate(){if(!currentUser||!confirm('Deactivate this subscription?'))return;try{await db.collection('users').doc(currentUser.id).update({subscriptionStatus:'inactive',subscriptionExpiresAt:null});await audit('Subscription deactivated');userNotice('Subscription deactivated.','success');await load();await openUser(currentUser.id)}catch(e){console.error(e);userNotice('Could not deactivate the subscription.')}}
  async function setTrial(){if(!currentUser)return;const days=Number($('trialDuration').value)||7;const end=new Date(Date.now()+days*86400000);if(!confirm(`Set this account to a ${days}-day trial?`))return;try{await db.collection('users').doc(currentUser.id).update({trialStartDate:firebase.firestore.FieldValue.serverTimestamp(),trialEndDate:firebase.firestore.Timestamp.fromDate(end),subscriptionStatus:'trial'});await audit(`Trial set for ${days} days`);userNotice('Trial updated.','success');await load();await openUser(currentUser.id)}catch(e){console.error(e);userNotice('Could not update the trial.')}}
  auth.onAuthStateChanged(async user=>{if(!user){location.href='login.html';return}adminEmail=String(user.email||'').toLowerCase();if(!ADMIN_EMAILS.has(adminEmail)||!user.emailVerified){await auth.signOut();location.href='login.html';return}setText('adminEmail',adminEmail);setText('adminAvatar',adminEmail.charAt(0).toUpperCase());await load()});
  $('logoutBtn').addEventListener('click',()=>auth.signOut().then(()=>location.href='login.html'));$('refreshBtn').addEventListener('click',load);$('userSearch').addEventListener('input',render);$('statusFilter').addEventListener('change',render);$('mobileMenu').addEventListener('click',()=>$('sidebar').classList.toggle('open'));$('closeUserModal').addEventListener('click',()=>{$('userModal').hidden=true;document.body.classList.remove('modal-open');currentUser=null});$('userModal').addEventListener('click',e=>{if(e.target===$('userModal')){$('userModal').hidden=true;document.body.classList.remove('modal-open');currentUser=null}});$('activateBtn').addEventListener('click',activate);$('deactivateBtn').addEventListener('click',deactivate);$('trialBtn').addEventListener('click',setTrial);
})();
